apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: costco
build:
  artifacts:
    - image: costco
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - k8s
