apiVersion: v1
kind: Service
metadata:
  name: costco
  namespace: costco
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: costco
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: costco
  labels:
    app: costco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: costco
  template:
    metadata:
      name: costco
      labels:
        app: costco
    spec:
      containers:
        - name: costco
          image: costco
          imagePullPolicy: Never
      restartPolicy: Always