apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
  namespace: private-registry
data:
  POSTGRES_DB: "private-container-registry"
  POSTGRES_USER: "pci"
  POSTGRES_PASSWORD: "1gMAfO7Xa49TpYHoqtYH"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  labels:
    app: postgres
  namespace: private-registry
data:
  init-metadata.sql: |
    CREATE TABLE private_registry
    (
        catalog_name               VARCHAR(255) NOT NULL,
        table_namespace            VARCHAR(255) NOT NULL,
        table_name                 VARCHAR(255) NOT NULL,
        metadata_location          VARCHAR(1000),
        previous_metadata_location VARCHAR(1000),
        PRIMARY KEY (catalog_name, table_namespace, table_name)
    );
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: private-registry
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: private-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres:14'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-init
              mountPath: "/docker-entrypoint-initdb.d"
              readOnly: true

      volumes:
        - name: postgres-init
          configMap:
            name: postgres-init