apiVersion: v1
kind: Service
metadata:
  name: private-registry
  namespace: private-registry
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: private-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-registry
  labels:
    app: private-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-registry
  template:
    metadata:
      name: private-registry
      labels:
        app: private-registry
    spec:
      containers:
        - name: private-registry
          image: private-registry
          imagePullPolicy: Never
      restartPolicy: Always